import type { Metadata } from "next";
import { Session, getServerSession } from "next-auth";
import Provider from "./Provider";
import { fonts } from "./fonts";
import { cn } from "@utils/classname";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = (await getServerSession()) as Session;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fonts.poppins.variable
        )}
      >
        <Provider session={session}>{children}</Provider>
      </body>
    </html>
  );
}
